version: "3"

services:
  cloud-run:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
