name: static analysis and  test
'on':
  push:
    # paths: #functions/が変わった時のみ動かす
    #   - 'functions/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: install node_modules
        run: npm install
        working-directory: ./functions
      - name: linter
        run: npm run lint
        working-directory: ./functions
      - name: test
        run: firebase emulators:exec 'npm test --silent' --project=twitch-clip-dev --only firestore --import test/test_data/firestore
        env:
          TYPE: ${{secrets.TYPE}}
          PROJECT_ID: ${{secrets.PROJECT_ID}}
          PRIVATE_KEY_ID: ${{secrets.PRIVATE_KEY_ID}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          CLIENT_EMAIL: ${{secrets.CLIENT_EMAIL}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          AUTH_URI: ${{secrets.AUTH_URI}}
          TOKEN_URI: ${{secrets.TOKEN_URI}}
          AUTH_PROVIDER_X509_CERT_URL: ${{secrets.AUTH_PROVIDER_X509_CERT_URL}}
          CLIENT_X509_CERT_URL: ${{secrets.CLIENT_X509_CERT_URL}}
          UNIVERSE_DOMAIN: ${{secrets.UNIVERSE_DOMAIN}}
          TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
          TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}
          FIRESTORE_EMULATOR_HOST: ${{env.FIRESTORE_EMULATOR_HOST}}
        working-directory: ./functions
